package com.tanzee.findmyparkingapp.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "MY_SPOTS".
*/
public class MySpotsDao extends AbstractDao<MySpots, Long> {

    public static final String TABLENAME = "MY_SPOTS";

    /**
     * Properties of entity MySpots.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Date = new Property(2, String.class, "date", false, "DATE");
        public final static Property TimeInLong = new Property(3, Long.class, "timeInLong", false, "TIME_IN_LONG");
        public final static Property Origin = new Property(4, String.class, "origin", false, "ORIGIN");
        public final static Property Destination = new Property(5, String.class, "destination", false, "DESTINATION");
        public final static Property Frequency = new Property(6, Integer.class, "frequency", false, "FREQUENCY");
    }


    public MySpotsDao(DaoConfig config) {
        super(config);
    }
    
    public MySpotsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MY_SPOTS\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"DATE\" TEXT UNIQUE ," + // 2: date
                "\"TIME_IN_LONG\" INTEGER," + // 3: timeInLong
                "\"ORIGIN\" TEXT," + // 4: origin
                "\"DESTINATION\" TEXT," + // 5: destination
                "\"FREQUENCY\" INTEGER);"); // 6: frequency
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MY_SPOTS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MySpots entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        Long timeInLong = entity.getTimeInLong();
        if (timeInLong != null) {
            stmt.bindLong(4, timeInLong);
        }
 
        String origin = entity.getOrigin();
        if (origin != null) {
            stmt.bindString(5, origin);
        }
 
        String destination = entity.getDestination();
        if (destination != null) {
            stmt.bindString(6, destination);
        }
 
        Integer frequency = entity.getFrequency();
        if (frequency != null) {
            stmt.bindLong(7, frequency);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MySpots entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        Long timeInLong = entity.getTimeInLong();
        if (timeInLong != null) {
            stmt.bindLong(4, timeInLong);
        }
 
        String origin = entity.getOrigin();
        if (origin != null) {
            stmt.bindString(5, origin);
        }
 
        String destination = entity.getDestination();
        if (destination != null) {
            stmt.bindString(6, destination);
        }
 
        Integer frequency = entity.getFrequency();
        if (frequency != null) {
            stmt.bindLong(7, frequency);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MySpots readEntity(Cursor cursor, int offset) {
        MySpots entity = new MySpots( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // date
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // timeInLong
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // origin
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // destination
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6) // frequency
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MySpots entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTimeInLong(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setOrigin(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDestination(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFrequency(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MySpots entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MySpots entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MySpots entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
