package com.tanzee.findmyparkingapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MY_SPOTS".
 */
@Entity
public class MySpots {

    @Id(autoincrement = true)
    private Long id;
    private String name;

    @Unique
    private String date;
    private Long timeInLong;
    private String origin;
    private String destination;
    private Integer frequency;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public MySpots() {
    }

    public MySpots(Long id) {
        this.id = id;
    }

    @Generated
    public MySpots(Long id, String name, String date, Long timeInLong, String origin, String destination, Integer frequency) {
        this.id = id;
        this.name = name;
        this.date = date;
        this.timeInLong = timeInLong;
        this.origin = origin;
        this.destination = destination;
        this.frequency = frequency;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Long getTimeInLong() {
        return timeInLong;
    }

    public void setTimeInLong(Long timeInLong) {
        this.timeInLong = timeInLong;
    }

    public String getOrigin() {
        return origin;
    }

    public void setOrigin(String origin) {
        this.origin = origin;
    }

    public String getDestination() {
        return destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

    public Integer getFrequency() {
        return frequency;
    }

    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
