package com.tanzee.findmyparkingapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PROFILE".
 */
@Entity
public class Profile {

    @Id(autoincrement = true)
    private Long id;

    @Unique
    private String email;
    private String image;
    private String password;

    @Unique
    private String phone;
    private String name;

    @Unique
    private String reg;

    @Unique
    private String lic;

    @Unique
    private String uid;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Profile() {
    }

    public Profile(Long id) {
        this.id = id;
    }

    @Generated
    public Profile(Long id, String email, String image, String password, String phone, String name, String reg, String lic, String uid) {
        this.id = id;
        this.email = email;
        this.image = image;
        this.password = password;
        this.phone = phone;
        this.name = name;
        this.reg = reg;
        this.lic = lic;
        this.uid = uid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getReg() {
        return reg;
    }

    public void setReg(String reg) {
        this.reg = reg;
    }

    public String getLic() {
        return lic;
    }

    public void setLic(String lic) {
        this.lic = lic;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
